name: mandarini
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07716
title: TESTING
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6401a'
    - '#c7aea2'
    - '#8a1f0d'
    - '#6b6a70'
    - '#0f0d0e'
  brandStrength: 0.9735132085625082
  lightness: 0.4611945648211986
  saturation: 0.3728155316784978
  rhythmicContrast: 0.7601896608248353
purpose: []
