name: mandarini
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07716
title: TESTING
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6401a'
    - '#c7aea2'
    - '#8a1f0d'
    - '#6b6a70'
    - '#0f0d0e'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
