name: mandarini
favicon: null
layout_spectrum: 0.4956
typography_spectrum: 0.41481
title: η Σελίδα μου
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#898582'
    - '#b7b3b0'
    - '#cac6c3'
    - '#dedede'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
